import type { Metadata } from "next";
import "./globals.css";
import ApiProvider from "@/providers";
// import { Providers } from "@/providers/index";
// import { cookies } from "next/headers";
// import { initializeAxiosInstance } from "@/hooks/instance";
// import { ApiProvider } from "@/providers";
// import { initializeAxiosInstance } from "@/helpers/instance";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const token = cookies().get("accessToken")?.value;

  // if (token) {
  //   initializeAxiosInstance(token);
  // }

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApiProvider>
          {children}
        </ApiProvider>
      </body>
    </html>
  );
}
